# Generated by Django 2.0.13 on 2019-03-22 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import organizations.base
import organizations.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_field_fix_and_editable"),
        ("companies2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyTeam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the organization",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created",
                    organizations.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    organizations.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "slug",
                    organizations.fields.SlugField(
                        blank=True,
                        editable=False,
                        help_text="The name in all lowercase, suitable for URL identification",
                        max_length=200,
                        populate_from="name",
                        unique=True,
                    ),
                ),
            ],
            options={"verbose_name": "team", "verbose_name_plural": "team"},
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CompanyTeamMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    organizations.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    organizations.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "team member",
                "verbose_name_plural": "team members",
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TeamCreatedBy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    organizations.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modified",
                    organizations.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "team created by",
                "verbose_name_plural": "team created by",
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.RemoveField(model_name="team", name="organization"),
        migrations.AlterUniqueTogether(
            name="teammember", unique_together=set()
        ),
        migrations.RemoveField(
            model_name="teammember", name="organization_user"
        ),
        migrations.RemoveField(model_name="teammember", name="team"),
        migrations.CreateModel(
            name="Company",
            fields=[],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "proxy": True,
                "indexes": [],
            },
            bases=("organizations.organization",),
        ),
        migrations.CreateModel(
            name="CompanyCreatedBy",
            fields=[],
            options={
                "verbose_name": "company created by",
                "verbose_name_plural": "company created by",
                "proxy": True,
                "indexes": [],
            },
            bases=("organizations.organizationowner",),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[],
            options={
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
                "proxy": True,
                "indexes": [],
            },
            bases=("organizations.organizationuser",),
        ),
        migrations.DeleteModel(name="Team"),
        migrations.DeleteModel(name="TeamMember"),
        migrations.AddField(
            model_name="companyteam",
            name="company",
            field=models.ForeignKey(
                help_text="Company that the team belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_teams",
                to="companies2.Company",
                verbose_name="company",
            ),
        ),
    ]
