# Generated by Django 2.0.13 on 2019-03-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20190322_0543")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="Enter user description here (Min 500 characters).",
                max_length=500,
                verbose_name="bio",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Enter full name of user.",
                max_length=255,
                verbose_name="Name of User",
            ),
        ),
    ]
