from django.conf import settings
from django.test import TestCase

from model_mommy import mommy
from organizations.models import (
    Organization,
    OrganizationUser,
    OrganizationOwner,
)

from employee_management_backend.companies.models import Team, TeamMember


class TestTeamModel(TestCase):
    """
    Test Team creation using data generated by model_mommy
    """

    def setUp(self):
        self.new_organization = Organization(name="Test Organization")
        self.new_organization.save()
        self.new_team = mommy.make(
            "companies.Team", organization=self.new_organization
        )

    def test_team_creation_mommy(self):
        self.assertTrue(isinstance(self.new_organization, Organization))
        self.assertTrue(isinstance(self.new_team, Team))
        self.assertEqual(
            self.new_team.__str__(),
            "Organization: {} Team: {}".format(
                self.new_organization.name, self.new_team.name
            ),
        )


class TestTeamMemberModel(TestCase):
    """
    Test TeamMember creation using data generated by model_mommy
    """

    def setUp(self):
        self.new_organization = Organization(name="Test Organization")
        self.new_organization.save()
        self.new_organization_user = mommy.make(
            "organizations.OrganizationUser",
            organization=self.new_organization,
        )
        self.new_team = mommy.make(
            "companies.Team", organization=self.new_organization
        )
        self.new_team_member = mommy.make(
            "companies.TeamMember",
            team=self.new_team,
            organization_user=self.new_organization_user,
        )

    def test_team_member_creation_mommy(self):
        self.assertTrue(isinstance(self.new_organization, Organization))
        self.assertTrue(
            isinstance(self.new_organization_user, OrganizationUser)
        )
        self.assertTrue(isinstance(self.new_team, Team))
        self.assertTrue(isinstance(self.new_team_member, TeamMember))
        self.assertEqual(
            self.new_team.__str__(),
            "Organization: {} Team: {}".format(
                self.new_organization.name, self.new_team.name
            ),
        )
        self.assertEqual(
            self.new_team_member.__str__(),
            "Organization: {} Team: {} Team Member: {}".format(
                self.new_organization.name,
                self.new_team.name,
                self.new_organization_user.user.username,
            ),
        )
